---
name: ClangFormat Check
on:
  push:
    branches:
      - grass[0-9]+
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_protected != true }}
permissions: {}
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          persist-credentials: false
      - uses: DoozyX/clang-format-lint-action@c71d0bf4e21876ebec3e5647491186f8797fde31 # v0.18.2
        with:
          source: "."
          clangFormatVersion: 18.1.8
          inplace: True
      - name: Create and uploads code suggestions to apply
        id: diff
        uses: OSGeo/grass/.github/actions/create-upload-suggestions@main
        with:
          tool-name: clang-format
          # To keep repo's file structure in formatted changes artifact
          extra-upload-changes: .clang-format
